# RabbitMQ Cluster Operator (Official)
# RabbitMQ クラスタを Kubernetes ネイティブに管理
# 公式 GitHub リポジトリから直接デプロイ
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/rabbitmq/cluster-operator.git
    targetRevision: v2.18.0
    path: config/default

  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
