# RabbitMQ Cluster Operator
# RabbitMQ クラスタを Kubernetes ネイティブに管理
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq-cluster-operator
    targetRevision: 4.4.34
    helm:
      releaseName: rabbitmq-operator
      values: |
        # 必要に応じてカスタマイズ

  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
