# Redis Operator (Spotahome)
# Redis クラスタ/Sentinel を Kubernetes ネイティブに管理
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://spotahome.github.io/redis-operator
    chart: redis-operator
    targetRevision: 3.3.0
    helm:
      releaseName: redis-operator
      values: |
        # 必要に応じてカスタマイズ

  destination:
    server: https://kubernetes.default.svc
    namespace: redis-operator-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
